export const PUBSUB_NEW_MESSAGE = "PUBSUB_NEW_MESSAGE"
export const PUBSUB_NEW_CHANNEL = "PUBSUB_NEW_CHANNEL"
export const PUBSUB_NEW_LOCATION = "PUBSUB_NEW_LOCATION"
export const PUBSUB_ONLINE_STATUS = "PUBSUB_ONLINE_STATUS"